[package]
name = "invariantdb"
version = "0.1.0"
authors = ["Anton Okolelov <okoanton@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4.6"
env_logger = "0.6.1"